name: mypy

on: workflow_call

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install mypy
        run: pip install mypy
      - name: Run mypy
        run: mypy --strict $(git ls-files '*.py')
